### ISSUE TITLE
Specifying options from the command line

### ISSUE THREAD

**Issue by pixelastic** [ben-eb/remark-word-wrap#44]
Hello,

I'm trying to use your plugin through the `remark-cli` commandline, using the following configuration file:

```json
{
  "plugins": {
    "word-wrap": {
      "width": 80
    }
  },
}
```

But the word wrap keep happening at 72 chars. I tried other values, I also tried the other options (`indent` and `newline`), and tried the `["word-wrap", { width: 80 }]` syntax in the config, but none worked.

I wonder if the issue is coming from the way I try to pass settings (following [documentation here](https://github.com/unifiedjs/unified-engine/blob/master/doc/configure.md#plugins)) or if it's something that is not possible with your plugin.

Any tips would be welcome,

Cheers,

**Comment by wooorm** [comment]
This plugin unfortunately hasn't been updated in a while. It also never really worked from what I gather :(

**Comment by pixelastic** [comment]
Thanks for info @wooorm. I ended up disabling it as it was cutting lines in weird places.

Do you have any plan on integration a similar feature in the official plugins maybe? I'm using remark-lint and trying to find a way to auto-fix most of the violations.

**Comment by wooorm** [comment]
prettier itself is great at formatting. It used remark for markdown under the hood, so of course it’s a good option ;)

I don’t really have a plan on doing this. It’s super hard to do properly in a “plugin”, because you need to know how every node is going to be printed. We talked a bit about it in GH-4 (and on other mediums that aren’t recorded, if I recall correctly).

If someone wants to work on it, I suggest sort of [what prettier does](https://github.com/prettier/prettier/blob/master/src/language-markdown/printer-markdown.js) and wrapping the compiler (similar to what [remark-frontmatter](https://github.com/remarkjs/remark-frontmatter/blob/master/index.js) for example does).

**Comment by pixelastic** [comment]
I wasn't aware prettier also formatted Markdown! Thanks for the tip, I'll have a look at it.
